### ISSUE TITLE
Hang with updated netcat-openbsd>=1.130.3

### ISSUE THREAD

**Issue by joepvandijken** [pytest-dev/pytest-services#13]
[debian changelog](https://launchpad.net/ubuntu/+source/netcat-openbsd/1.130-3)

When using updated version of netcat (found problem on arch) py.test will indefinitely wait for "echo 'flush_all' | nc 127.0.0.1 11211" "echo 'flush_all' | nc -N 127.0.0.1 11211" is needed for the old behaviour which is not compatible with previous versions like ubuntu 14.04.

Created a pull request which uses pylibmc to flush_all and remove the dependency on nc

**Comment by bubenkoff** [comment]
1.1.15 is out
thanks!
