### ISSUE TITLE
Impolite service termination

### ISSUE THREAD

**Issue by jaraco** [pytest-dev/pytest-services#15]
In the finalizer for the plugin, the [current termination logic](https://github.com/pytest-dev/pytest-services/blob/b55325985496b7a0fec13f9bf55e12915c83215e/pytest_services/service.py#L72-L79) is to first kill, then terminate the proc. On Windows, these two calls are the same, but on Unix, these calls should be reversed. `terminate` is the more polite operation, asking the child to shutdown cleanly, whereas `kill` is equivalent to `kill -9` and will cause the child to simply stop without cleaning up. This approach means that a complex service that starts its own child services will stop but leave these other processes running.

**Comment by bubenkoff** [comment]
nice catch!
let's fix of course
