### ISSUE TITLE
Add cross-platform support

### ISSUE THREAD

**Issue by webknjaz** [pytest-dev/pytest-services#23]
UNIX assumption causes issue with Windows: this dist unconditionally imports `fcntl`, which crashes tests during setup time, when `pytest` looks up for and tries to import fixtures: https://ci.appveyor.com/project/CherryPy/cherrypy/build/1.0.444/job/seei217vtwplqk6h#L500

(Ref https://github.com/pytest-dev/pytest-services/issues/22#issuecomment-419751978)

**Comment by bubenkoff** [comment]
without switch to docker this plugin will be useless for windows, i'm affraid

**Comment by jaraco** [comment]
In #24, I propose a minimal fix for this issue.

Though you may want to consider a more robust approach, such as to use [zc.lockfile](/zopefoundation/zc.lockfile) as a proven, cross-platform lockfile implementation.

**Comment by jaraco** [comment]
I looked into adopting `zc.lockfile`, but the current implementation doesn't support the use-case demanded by pytest-services. In particular, it unconditionally [writes to and truncates the file](https://github.com/zopefoundation/zc.lockfile/blob/1c79e5c82abeb032611406f154c6f77d9323faad/src/zc/lockfile/__init__.py#L95-L98). A refactor of zc.lockfile will be required to support use in pytest-services.

**Comment by bubenkoff** [comment]
how about https://pypi.org/project/fasteners/ or https://docs.openstack.org/oslo.concurrency/latest/
