### ISSUE TITLE
`zc.lockfile.LockError` Is Raised in `lock_resource`

### ISSUE THREAD

**Issue by StabbarN** [pytest-dev/pytest-services#38]
The switch to `zc.lockfile` in https://github.com/pytest-dev/pytest-services/pull/27 breaks our tests together with pytest-xdist.

```
@pytest.fixture(scope="session")
def _xyz_server_process(port_getter):
    port = port_getter()
```

We have
```
pytest = "6.0.2"
pytest-django = "3.10.0"
pytest-instafail = "0.4.2"
pytest-selenium = "2.0.0"
pytest-services = "2.1.0"
pytest-timeout = "1.4.2"
pytest-xdist = "2.1.0"
```

`pytest -n2` fails and `pytest` works.

```
.venv/lib/python3.7/site-packages/zc/lockfile/__init__.py:59: in _lock_file
    fcntl.flock(file.fileno(), _flags)
E   BlockingIOError: [Errno 35] Resource temporarily unavailable

During handling of the above exception, another exception occurred:
tests/browser/conftest.py:195: in _xyz_server_process
    port = port_getter()
.venv/lib/python3.7/site-packages/pytest_services/locks.py:140: in get_port
    port = get_free_port(lock_dir, services_log)
.venv/lib/python3.7/site-packages/pytest_services/locks.py:117: in get_free_port
    return lock_resource('port', get_port, lock_dir, services_log)
.venv/lib/python3.7/site-packages/pytest_services/locks.py:85: in lock_resource
    with locked_resources(name, lock_dir) as bound_resources:
../../.pyenv/versions/3.7.2/lib/python3.7/contextlib.py:112: in __enter__
    return next(self.gen)
.venv/lib/python3.7/site-packages/pytest_services/locks.py:56: in locked_resources
    with file_lock(os.path.join(lock_dir, name), remove=False) as fd:
../../.pyenv/versions/3.7.2/lib/python3.7/contextlib.py:112: in __enter__
    return next(self.gen)
.venv/lib/python3.7/site-packages/pytest_services/locks.py:27: in file_lock
    with contextlib.closing(zc.lockfile.SimpleLockFile(filename)) as lockfile:
.venv/lib/python3.7/site-packages/zc/lockfile/__init__.py:90: in __init__
    _lock_file(fp)
.venv/lib/python3.7/site-packages/zc/lockfile/__init__.py:61: in _lock_file
    raise LockError("Couldn't lock %r" % file.name)
E   zc.lockfile.LockError: Couldn't lock '/tmp/service-locks/port'
```

Tested on macOS Catalina and Debian.

Each start of tests is not always failing but it's very often.

**Comment by bubenkoff** [comment]
I don't think it's an incompatibility at all, it's more like a bug in the usage of zc.lockfile in the pytest-services
do you also use the latest version of zc.lockfile?

**Comment by StabbarN** [comment]
@bubenkoff Yes, we use the latest version (as specified in https://github.com/pytest-dev/pytest-services/blob/master/setup.py#L22). Yeah, I agree, sloppy title of the issue, it's not about incompatibility.

@jaraco please read this issue and https://github.com/zopefoundation/zc.lockfile/issues/23 . What's your thoughts about this?

**Comment by bubenkoff** [comment]
@jaraco @StabbarN looks like just an incorrect exception handling when the lock cannot be obtained due to the concurrent worker

**Comment by StabbarN** [comment]
@bubenkoff My PR https://github.com/pytest-dev/pytest-services/pull/39 seems to fix the problem for us. Will you review it and if OK make a new release?

**Comment by jaraco** [comment]
> What's your thoughts?

Thanks for looping me in, and sorry for the trouble. I'd not encountered this issue before, and it does seem the zc.lockfile maintainers have provided guidance, so your approach seems sound given the limitations.

**Comment by mshriver** [comment]
I've opened #42 because I'm observing nearly identical exception failure as described in this issue, but on `file_lock` instead of `lock_resource`.
